Fix services workers initializers
This is a bug introduced by the extraction of the bunny gem to the
service-base gem.

```
 NameError: uninitialized constant Bunny
interscity-platform_actuatorcontroller.1.xn5dj5tcttl3@worker-2    |   config.ru:in `<main>'
interscity-platform_actuatorcontroller.1.bcrjxorwcw83@worker-2    |   /usr/local/bundle/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/active_support.rb:79:in `block in load_missing_constant'
interscity-platform_actuatorcontroller.1.xn5dj5tcttl3@worker-2    |   /usr/local/bundle/gems/rack-2.0.7/lib/rack/builder.rb:49:in `eval'
interscity-platform_actuatorcontroller.1.bcrjxorwcw83@worker-2    |   /usr/local/bundle/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/active_support.rb:8:in `without_bootsnap_cache'
interscity-platform_actuatorcontroller.1.xn5dj5tcttl3@worker-2    |   /usr/local/bundle/gems/rack-2.0.7/lib/rack/builder.rb:49:in `new_from_string'
interscity-platform_actuatorcontroller.1.bcrjxorwcw83@worker-2    |   /usr/local/bundle/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/active_support.rb:79:in `rescue in load_missing_constant'
interscity-platform_actuatorcontroller.1.xn5dj5tcttl3@worker-2    |   /usr/local/bundle/gems/rack-2.0.7/lib/rack/builder.rb:40:in `parse_file'
interscity-platform_actuatorcontroller.1.bcrjxorwcw83@worker-2    |   /usr/local/bundle/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/active_support.rb:58:in `load_missing_constant'
interscity-platform_actuatorcontroller.1.xn5dj5tcttl3@worker-2    |   /usr/local/bundle/gems/puma-3.12.1/lib/puma/configuration.rb:320:in `load_rackup'
interscity-platform_actuatorcontroller.1.bcrjxorwcw83@worker-2    |   /actuator-controller/config/initializers/workers.rb:4:in `<main>'
```