Fix services puma configuration
When updating Rails I missed the comment marker. This cause application
startup to fail with:

```
 bundler: failed to load command: puma (/usr/local/bundle/bin/puma)
interscity-platform_resourcediscoverer.1.ysea07q0vorn@worker-2    | NameError: undefined local variable or method `memory' for #<Puma::DSL:0x000055d696a631d8>
interscity-platform_resourcediscoverer.1.ysea07q0vorn@worker-2    |   config/puma.rb:29:in `_load_from'
interscity-platform_resourcediscoverer.1.ysea07q0vorn@worker-2    |   /usr/local/bundle/gems/puma-3.12.1/lib/puma/dsl.rb:43:in `instance_eval'
```